<h1>Welcome to <b>Store!</b></h1>

<!-- Subscribe section -->
<div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
</div>

<!-- Footer -->
<footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
    <div class="w3-row-padding">
        
        <div class="w3-col s4 w3-justify">
            <h4>Store</h4>
            <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
            <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
            <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
            <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
            <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
            <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
            <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
            <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
            <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
        </div>
        <div class="w3-col s4 w3-justify">
            <h4>We accept</h4>
            <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
            <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        </div>
        
        <!--<div class="w3-col s4 w3-justify">-->
        <!--    <h4>Store</h4>-->
        <!--    <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>-->
        <!--    <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>-->
        <!--    <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>-->
        <!--    <h4>We accept</h4>-->
        <!--    <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>-->
        <!--    <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>-->
        <!--    <br>-->
        <!--    <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>-->
        <!--    <i class="fa fa-instagram w3-hover-opacity w3-large"></i>-->
        <!--    <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>-->
        <!--    <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>-->
        <!--    <i class="fa fa-twitter w3-hover-opacity w3-large"></i>-->
        <!--    <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>-->
        <!--</div>-->
    </div>
</footer>