<div class="w3-row">
    <div style="margin:auto;">
        <h4 class="w3-center">Some contacts</h4>
        <p class="w3-padding"><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
        <p class="w3-padding"><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p class="w3-padding"><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <hr>
        <h4 class="w3-center">A few words about us</h4>
        <p class="w3-padding">Here should be a huge text about our company and our store</p>
        <hr>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
    </div>
</div>