<div class="w3-row">
    <div class="s4" style="margin:10px auto;">
        <h4>Contact</h4>
        <p>Questions? Go ahead.</p>
    
        <form action="/feedback/get" method="post">
            <p><input class="w3-input w3-border" type="text" placeholder="Name" name="name" required></p>
            <p><input class="w3-input w3-border" type="email" placeholder="Email" name="email" required></p>
            <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="subject" required></p>
            <p><textarea class="w3-input w3-border" placeholder="Message" name="message" rows="10" cols="30" style="resize:none;"></textarea></p>
            <button type="submit" class="w3-button w3-block w3-light-grey">Send</button>
        </form>
    </div>
</div>